### ISSUE TITLE
Missing environment.yaml file

### ISSUE THREAD

**Issue by gqk** [iamwangyabin/ESN#1]
Hi Yabin,

Good work! However, I noticed that the environment.yaml file is missing from the repo. Would it be possible for you to provide the environment.yaml file? I would greatly appreciate it, as it would allow me to properly run and test the code.

**Comment by iamwangyabin** [comment]
Thank you for reminding me! I have updated the environmental file.

**Comment by gqk** [comment]
I have already successfully run the code, thank you @iamwangyabin  for the updation!
However, the unknown param `progress_bar_refresh_rate` raises an error when running the code. https://github.com/iamwangyabin/ESN/blob/d163bc64541803241a9b2ea76a5d6c985e9fc9a5/trainer.py#L12

Moreover, I find that you use the `vit_base_patch16_224` model, while L2P and DualPrompt use the `vit_base_patch16_224_in21k`. As far as I know,  `vit_base_patch16_224` is actually the `vit_base_patch16_224_in21k` fine-tuned on the ImageNet-1K dataset, which may bring some performance improvement.
