### ISSUE TITLE
Should the prompts be fixed or trained across all the tasks?

### ISSUE THREAD

**Issue by zugexiaodui** [iamwangyabin/ESN#4]
According to the code:
https://github.com/iamwangyabin/ESN/blob/d163bc64541803241a9b2ea76a5d6c985e9fc9a5/trainer.py#L16-L24
It seems the prompts should be fixed after the first task. However, the prompts are actually kept training since the `vitprompt` still requires grad. `freezep` does not work. The `vitprompt` is still trained in the following tasks.

If the prompts should be trained across all the tasks, does the following code in `eval()` function result in the leakage of task information?
https://github.com/iamwangyabin/ESN/blob/d163bc64541803241a9b2ea76a5d6c985e9fc9a5/trainer.py#L109
It seems that the backbone leverages the prompts in the current test task to extract image features, but the backbone should not know the task which the image belongs to.

**Comment by iamwangyabin** [comment]
Firstly, it's true that we maintain only the recent prompt (current session), and indeed, there is no freezing of prompts after each task—in line with the approach taken by L2P, we continuously fine-tune this prompt parameter. This means that at any given point, we're utilizing a single, latest prompt that has been fine-tuned through the continual tasks.

Regarding the eval() function, the code in question is designed to generate an **accuracy matrix** after all the incremental learning sessions are completed. This process involves iterating over the model parameters at all incremental stages to test and calculate the results and measure forgetting. Hence, there is no leakage of task information during the testing phase. The task ID is solely used to restore and evaluate the model's accuracy at that specific task (task id). The code is written in this manner specifically to facilitate the creation of the accuracy matrix, ensuring a thorough evaluation of the model across all increments.

**Comment by zugexiaodui** [comment]
Thank you for the timely reply!
